[package]
name = "outbound"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
serde = "1.0.229"
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["full"] }
uuid = "1.27.0"

common = { path = "../common" }
redis = "1.7.1"
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
